services:
#  amsdb:
#    image: mysql:latest
#    container_name: amsdb_mysql
#    # restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: AA@@11bb22cc33
#      MYSQL_DATABASE: asset_db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: AA@@11bb22cc33
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app_network
  amsapp:
    container_name: amsapp_springboot
    build:
      context: ./
      dockerfile: Dockerfile
    image: amsapp:1.0.4
    ports:
      - "8080:8080"
    volumes:
      - /d/u01:/app/files
    environment:
      - SPRING_CONFIG_LOCATION=/app/files/config/assetconfig.yml  # Path to the config file
#    depends_on:
#      - db
    networks:
      - amsapp_network

#  amsapp_cache:
#    image: redis:latest

networks:
  amsapp_network:
    driver: bridge
    
#volumes:
#  amsdb:
